package com.codexdroid.theguru.di.room.tables

import androidx.room.Entity

@Entity(tableName = "table_self")
data class TableSelf (

    val registeredAs: String,
    val fullName: String,
    val email: String,
    val whatsApp: String,
    val password: String,
    val autoGenerated: Boolean = false,
    val isEmailVerified: Boolean = false,
    val isMobileVerified: Boolean = false
)
